[book]
authors = ["Soma Contributors"]
language = "en"
multilingual = false
src = "src"
title = "S❍MA"

[build]
create-missing = false

[preprocessor.external-links]

[output.html]
git-repository-url = "https://github.com/somadotorg/book"
edit-url-template = "https://github.com/somadotorg/book/edit/main/{path}"
default-theme = "ayu"
preferred-dark-theme = "ayu"
git-repository-icon = "fa-github"
